#!/usr/bin/env bash
#This script  installs the nginx server and configures it.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
