#!/usr/bin/env bash
# This script configures a new nginx web server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/not_found.html
sudo sed -i "s|listen \[::\]:80 default_server;|listen \[::\]:80 default_server;\
        location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
	}\
	error_page 404 /not_found.html;\
	location = /not_found.html {\
	root /var/www/html;\
		internal;\
        }|" "/etc/nginx/sites-enabled/default"
sudo service nginx restart
