#!/usr/bin/env bash
#script that configure new load balancer

apt-get update
apt-get install haproxy -y 

options="\tbind *:80\n\tbalance roundrobin"
servers="\tserver 264110-web-02 34.202.157.214 check
        server 264110-web-01 100.24.206.67 check"
echo -e "$options" >> /etc/haproxy/haproxy.cfg
echo -e "$servers" >> /etc/haproxy/haproxy.cfg

service haproxy start
