#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=0
min=1
while [ $i -lt 13 ]
do
	echo "Hour: $i"
	while [ $min -lt 60 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( i++ ))
	min=$((1))
done
